version: "3.8"
services:
  app:
    build: .
    ports:
      - "8085:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exam-db
      SPRING_DATASOURCE_USERNAME: exam
      SPRING_DATASOURCE_PASSWORD: password
  ### Postgres Database ###
  postgres:
    image: postgres:10.4
    ports:
      - "27018:5432"
    environment:
      POSTGRES_USER: exam
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exam-db
  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
