version: "3.8"
services:
  exam-app:
    container_name: exam-app
    image: exam-app
    build: ./
    ports:
      - "8087:8083"
#    depends_on:
#      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exam-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app_network
#  postgres:
#    container_name: postgres
#    image: postgres:10.4
#    hostname: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: exam-db
#    networks:
#      - app_network

networks:
  app_network:
    name: app_network
