
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:27018/order-db
    database: order-db
    password: password
    username: order

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true

server:
  servlet:
    context-path: /api
  port: 8083


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /api-doc







