spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5433/exam-db
    database: exam-db
    password: password
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
  jackson:
    time-zone: Africa/Cairo

  mail:
    host: smtp.gmail.com
    port: 587
    username: engineersoftware515@gmail.com
    password: qjanumcbqvnkeifp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api
  port: 8083


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /api-doc


