spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5434/exam-db
    database: exam-db
    password: password
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true

  jackson:
    time-zone: Africa/Cairo

server:
  servlet:
    context-path: /api/exam
  port: 8082



# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /exam/api-doc