version: "3.8"
services:
  app:
    container_name: codeJudgment-app
    image: exam-service
    build: ./
    ports:
      - "8088:8083"
    depends_on:
      - postgres-code
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/code-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      app_network:
  ### Postgres Database ###
  postgres-code:
    container_name: postgres-code
    image: postgres:10.4
    hostname: postgres-code
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code-db
    networks:
      - app_network
  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres-code
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      app_network:
networks:
  app_network: