spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5433/code-db
    database: code-db
    password: password
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
  jackson:
    time-zone=Africa/Cairo:

server:
  servlet:
    context-path: /api/code
  port: 8083


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /code/api-doc